<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-GRDMPPQ" name="org.acdigital.achdd.ac_reservation.ui.ac_ui_hdd_poc.selenium.TestGroupRun" tests="1" failures="0" timestamp="2021-05-05T11:51:20 IST" time="0.004" errors="1">
  <testcase name="groupTest" time="0.004" classname="org.acdigital.achdd.ac_reservation.ui.ac_ui_hdd_poc.selenium.TestGroupRun">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void org.acdigital.achdd.ac_reservation.ui.ac_ui_hdd_poc.selenium.TestGroupRun.groupTest()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: groupTest([])
Arguments: [(java.lang.String) user1,(java.lang.String) pass1]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.acdigital.achdd.ac_reservation.ui.ac_ui_hdd_poc.selenium.TestGroupRun.groupTest()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: groupTest([])
Arguments: [(java.lang.String) user1,(java.lang.String) pass1]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:905)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- groupTest -->
  <system-out/>
</testsuite> <!-- org.acdigital.achdd.ac_reservation.ui.ac_ui_hdd_poc.selenium.TestGroupRun -->
